version: 2
updates:
  - package-ecosystem: 'github-actions'
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: '/'
    schedule:
      interval: 'weekly'
    reviewers:
      - 'VKCOM/vk-sec'
      - 'VKCOM/vkui-core'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    allow:
      - dependency-type: 'direct'
    groups:
      jest:
        patterns:
          - 'jest*'
          - '@swc/jest'
      rspack:
        patterns:
          - '@rspack/*'
      react:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react'
      size-limit:
        patterns:
          - 'size-limit'
          - '@size-limit/*'
      prettier:
        patterns:
          - 'prettier'
          - '@vkontakte/prettier-config'
    reviewers:
      - 'VKCOM/vk-sec'
      - 'VKCOM/vkui-core'
